[default_session]
startup_command = "ll"

[[session]]
name = "Downloads ðŸ“¥"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "tmux config î¯ˆ"
path = "~/dotfiles/tmux/"
startup_command = "nvim tmux/.tmux.conf"

[[session]]
name = "nvim config ðŸ’¤"
path = "~/.config/nvim/"
startup_command = "nvim"

[[session]]
name = "notes ðŸ““"
path = "~/Documents/tymon-obsidian/"
startup_command = "nvim"
